import RootLayout from './rootLayout';
import '@/app/styles/globals.css'
import { CookiesProvider } from 'react-cookie';

export const metadata = {
  title: '(Re)Sources Relationnelles',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  )
}